#!/bin/sh

#######################################################################################################
#   APPLICATIONS
#######################################################################################################

# needed to make java GUI works https://bit.ly/2ycKpYD
wmname LG3D

# keybinding daemon
sxhkd &

# compositor. Reduces flicker. Disabling saves resources.
picom -b --experimental-backends --backend glx &

# wallpaper manager
feh --no-fehbg --bg-fill --bg-center --bg-scale `xdg-user-dir PICTURES`/wallpaper/default

# system bar(s)
polybar control &
polybar status &
xdo hide -m -a "polybar-control_eDP-1"
xdo hide -m -a "polybar-status_eDP-1"

#######################################################################################################
#   CONFIGS
#######################################################################################################

# desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# paddings and gaps
bspc config top_padding         0
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0

bspc config window_gap          12
bspc config gapless_monocle     true

# borders
bspc config border_width        0
bspc config borderless_monocle  true

# colors
bspc config normal_border_color "#968e7a"
bspc config focused_border_color "#7d7668"
bspc config urgent_border_color "#ad0000"

# focusing behavior
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true
#bspc config pointer_follows_focus true

# splits
bspc config split_ratio         0.5
# balances all windows when new one is spawned 
#euclid_balancer &
# do not make windows smaller than they wish to be
#bspc config honor_size_hints true
# splits focused window when opening new window
bspc config external_rules_command /usr/bin/pseudo_automatic_mode
# splits biggest windows to keep windows about the same size
#bspc config external_rules_command /usr/bin/adjust-new-window

# various settings
# adjusts gap automatically according to the number of windows on the desktop
#autogap &

# exception rules
bspc rule -a InfoBox state=floating follow=on rectangle=442x220+0+800
bspc rule -a Gimp desktop=8 state=floating follow=on
bspc rule -a jade-Boot desktop=9 follow=off
bspc rule -a Mail desktop=10 follow=off
bspc rule -a BlueMail desktop=10 follow=off
bspc rule -a Mailspring desktop=10 follow=off
bspc rule -a thunderbird desktop=10 follow=off 
bspc rule -a MainKt state=floating
bspc rule -a Vivaldi-snapshot private=on
bspc rule -a Zathura state=tiled

bspc rule -a gcolor2 state=floating center=true
bspc rule -a lxappearance state=floating center=true
bspc rule -a gmrun state=floating center=true
bspc rule -a lxterminal state=floating center=true sticky=true
bspc rule -a viewnior state=floating center=true
bspc rule -a file-roller state=floating center=true
bspc rule -a floaterm state=floating center=true
bspc rule -a file-roller state=pseudo_tiled
bspc rule -a transmission-gtk state=pseudo_tiled
bspc rule -a conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a yad state=floating
bspc rule -a wpa_gui state=pseudo_tiled
bspc rule -a 9menu border=off manage=off
