#!/bin/sh

#######################################################################################################
#   APPLICATIONS
#######################################################################################################

# needed to make java GUI works https://bit.ly/2ycKpYD
wmname LG3D

# set wallpaper
feh --bg-center --bg-scale `xdg-user-dir PICTURES`/Great_Wave_off_Kanagawa2.jpg

# launch sxhkd
sxhkd &

# launch polybar
$HOME/.config/polybar/launch.sh

#######################################################################################################
#   CONFIGS
#######################################################################################################

# miscellaneous
center = on

# set desktops
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# paddings and gaps
bspc config top_padding         0
bspc config bottom_padding      0
bspc config left_padding        0
bspc config right_padding       0

bspc config window_gap          12

bspc config gapless_monocle     true

bspc config split_ratio         0.5

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off

# borders
bspc config border_width        0

bspc config borderless_monocle   true

# borders colors
bspc config normal_border_color "#968e7a"
bspc config focused_border_color "#7d7668"
bspc config urgent_border_color "#ad0000"

# focusing behavior
bspc config focus_follows_pointer true
bspc config history_aware_focus true
bspc config focus_by_distance true
