#! /bin/sh

# set wallpaper
feh --bg-center $HOME/Immagini/wallpapers/default

# launc sxhkd
sxhkd &

# set desktops
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off

# launch polybar
$HOME/.config/polybar/launch.sh

# launch albert
$HOME/.config/albert/launch.sh

# focus settings
mark-ovredir-focused = false
