[font]
size = 8

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[general]
import = ["/home/mandrab/.config/alacritty/themes/solarized_light.toml"]
